import type { Metadata, Viewport } from 'next';
import { Analytics } from '@vercel/analytics/next';
import {
  ADSENSE_VERIFICATION_ID,
  ADSENSE_VERIFICATION_META_NAME,
} from '@/lib/ads/verification';
import { SITE_DESCRIPTION, SITE_NAME, SITE_URL } from '@/lib/site/config';
import '@/styles/globals.css';

export const metadata: Metadata = {
  /*
   * With this set, a relative `alternates.canonical` on any page resolves against the
   * real origin instead of localhost. The campaign routes still declare theirs
   * absolutely — see `src/lib/campaigns/index.ts` — because that value has to be
   * unambiguous even if this line ever moves.
   */
  metadataBase: new URL(SITE_URL),
  title: 'hum(ai)n — will you be replaced?',
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  robots: { index: true, follow: true },
  alternates: { canonical: '/' },
  /*
   * The social preview. A share of a finished game is the main way this reaches a
   * second person, so the card is worth getting right: the image is generated by
   * `opengraph-image.tsx` from the same palette as the game and is picked up
   * automatically here and on every page that does not override it.
   */
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: SITE_NAME,
    title: 'hum(ai)n — will you be replaced?',
    description: SITE_DESCRIPTION,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'hum(ai)n — will you be replaced?',
    description: SITE_DESCRIPTION,
  },
  other: {
    // The whole piece is one dark surface; tell the browser so form controls and
    // scrollbars match instead of flashing white.
    'color-scheme': 'dark',
    /*
     * AdSense site-ownership verification. A claim about who owns this domain, and
     * nothing more — no script is loaded, no ad unit exists, no Google host is
     * contacted, and /ads.txt still returns 404. See src/lib/ads/verification.ts.
     */
    [ADSENSE_VERIFICATION_META_NAME]: ADSENSE_VERIFICATION_ID,
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#07070a',
  colorScheme: 'dark',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/*
          Page views, plus the six funnel events defined in `src/lib/analytics/events.ts`.
          Nothing this game learns about a player is passed to it: no profile, no
          choices, no verdict. The event helper enforces that with a closed list of
          names and a per-event allowlist of properties, so it is not a convention that
          can be broken by a later edit.

          In production the script is `/_vercel/insights/script.js`, served from this
          origin by Vercel's proxy, so the existing `script-src 'self'` and
          `connect-src 'self'` already allow it and the policy is unchanged. In
          development the package instead asks for a debug script on
          `va.vercel-scripts.com`, which this policy blocks — deliberately left blocked,
          since analytics does not function on localhost anyway and widening the policy
          to accommodate a development convenience would be the wrong trade.
        */}
        <Analytics />
      </body>
    </html>
  );
}
